config/routes.rb
Rails.application.routes.draw do
  resources :videos

  devise_for :users
  resources :tieneamenities

  resources :amenities

  get 'api/mostrarJson'
  get 'api/mostrarjson' => 'api#mostrarJson'
  get 'propiedades' => 'api#mostrarJson'
  
  get 'propiedads/:id/pausar' => 'propiedads#pausar', as: 'pausar'
  get 'propiedads/:id/reanudar' => 'propiedads#reanudar', as: 'reanudar'
  get 'propiedads/:id/finalizar' => 'propiedads#finalizar', as: 'finalizar'
  get 'propiedads/:id/republicar' => 'propiedads#republicar', as: 'republicar'  
  
  get 'propiedads/filtro'
  
  get 'propiedads/estadisticasBarrio'
  
  resources :operacions

  resources :monedas

  resources :fotos

  resources :tipo_propiedads

  resources :propiedads do
    resources :fotos
  end

  resources :barrios

  get 'welcome/index'
  
  get '/piechart' => 'piechart#piechart'
  get '/columnchart' => 'columnchart#columnchart'
  get '/columnchartprueba' => 'columnchartprueba#columnchartprueba'
  get '/piechartprueba' => 'piechartprueba#piechartprueba'

  root 'welcome#index'

end

app/models/tieneamenity.rb
class Tieneamenity < ActiveRecord::Base
  belongs_to :propiedad
  belongs_to :amenity
end

app/controllers/tieneamenities_controller.rb
class TieneamenitiesController < ApplicationController
  before_action :set_tieneamenity, only: [:show, :edit, :update, :destroy]
  # GET /tieneamenities
  # GET /tieneamenities.json
  def index
    @tieneamenities = Tieneamenity.all
  end

  # GET /tieneamenities/1
  # GET /tieneamenities/1.json
  def show
  end

  # GET /tieneamenities/new
  def new
    @tieneamenity = Tieneamenity.new
  end

  # GET /tieneamenities/1/edit
  def edit
  end

  # POST /tieneamenities
  # POST /tieneamenities.json
  def create
    @tieneamenity = Tieneamenity.new(tieneamenity_params)

    respond_to do |format|
      if @tieneamenity.save
        format.html { redirect_to @tieneamenity, notice: 'Tieneamenity was successfully created.' }
        format.json { render :show, status: :created, location: @tieneamenity }
      else
        format.html { render :new }
        format.json { render json: @tieneamenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tieneamenities/1
  # PATCH/PUT /tieneamenities/1.json
  def update
    respond_to do |format|
      if @tieneamenity.update(tieneamenity_params)
        format.html { redirect_to @tieneamenity, notice: 'Tieneamenity was successfully updated.' }
        format.json { render :show, status: :ok, location: @tieneamenity }
      else
        format.html { render :edit }
        format.json { render json: @tieneamenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tieneamenities/1
  # DELETE /tieneamenities/1.json
  def destroy
    @tieneamenity.destroy
    respond_to do |format|
      format.html { redirect_to tieneamenities_url, notice: 'Tieneamenity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_tieneamenity
    @tieneamenity = Tieneamenity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tieneamenity_params
    params.require(:tieneamenity).permit(:propiedad_id, :amenity_id)
  end
end

app/helpers/tieneamenities_helper.rb
module TieneamenitiesHelper
end

app/views/tieneamenities/_form.html.erb
<%= form_for(@tieneamenity) do |f| %>
  <% if @tieneamenity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tieneamenity.errors.count, "error") %> prohibited this tieneamenity from being saved:</h2>

      <ul>
      <% @tieneamenity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :propiedad_id %><br>
    <%= f.text_field :propiedad_id %>
  </div>
  <div class="field">
    <%= f.label :amenity_id %><br>
    <%= f.text_field :amenity_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tieneamenities/edit.html.erb
<h1>Editing tieneamenity</h1>

<%= render 'form' %>

<%= link_to 'Show', @tieneamenity %> |
<%= link_to 'Back', tieneamenities_path %>

app/views/tieneamenities/index.html.erb
<h1>Listing tieneamenities</h1>

<table>
	<thead>
		<tr>
			<th>Propiedad</th>
			<th>Amenity</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% if @tieneamenities %>
		<% @tieneamenities.each do |tieneamenity| %>
		<tr>
			<td><%= tieneamenity.propiedad.direccion %></td>
			<td><%= tieneamenity.amenity.nombre %></td>
			<td><%= link_to 'Show', tieneamenity %></td>
			<td><%= link_to 'Edit', edit_tieneamenity_path(tieneamenity) %></td>
			<td><%= link_to 'Destroy', tieneamenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
		<% end %>
		<% end %>
	</tbody>
</table>

<br>

<%= link_to 'New Tieneamenity', new_tieneamenity_path %>

app/views/tieneamenities/new.html.erb
<h1>New tieneamenity</h1>

<%= render 'form' %>

<%= link_to 'Back', tieneamenities_path %>

app/views/tieneamenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Propiedad:</strong>
  <%= @tieneamenity.propiedad.direccion %>
</p>

<p>
  <strong>Amenity:</strong>
  <%= @tieneamenity.amenity.nombre %>
</p>

<%= link_to 'Edit', edit_tieneamenity_path(@tieneamenity) %> |
<%= link_to 'Back', tieneamenities_path %>