config/routes.rb
Rails.application.routes.draw do
  resources :videos

  devise_for :users
  resources :tieneamenities

  resources :amenities

  get 'api/mostrarJson'
  get 'api/mostrarjson' => 'api#mostrarJson'
  get 'propiedades' => 'api#mostrarJson'
  
  get 'propiedads/:id/pausar' => 'propiedads#pausar', as: 'pausar'
  get 'propiedads/:id/reanudar' => 'propiedads#reanudar', as: 'reanudar'
  get 'propiedads/:id/finalizar' => 'propiedads#finalizar', as: 'finalizar'
  get 'propiedads/:id/republicar' => 'propiedads#republicar', as: 'republicar'  
  
  get 'propiedads/filtro'
  
  get 'propiedads/estadisticasBarrio'
  
  resources :operacions

  resources :monedas

  resources :fotos

  resources :tipo_propiedads

  resources :propiedads do
    resources :fotos
  end

  resources :barrios

  get 'welcome/index'
  
  get '/piechart' => 'piechart#piechart'
  get '/columnchart' => 'columnchart#columnchart'
  get '/columnchartprueba' => 'columnchartprueba#columnchartprueba'
  get '/piechartprueba' => 'piechartprueba#piechartprueba'

  root 'welcome#index'

end

app/models/barrio.rb
class Barrio < ActiveRecord::Base
  validates :nombre, presence: true
end

public

def promedioM2
    inicializar

    @props = @props.select { |propiedad| propiedad.superficie != nil }
    
    totalPesos = 0
    totalM2 = 0
    
    @props.each { |propiedad| 
       totalPesos += propiedad.precio_pesos
       totalM2 += propiedad.superficie
    }
    
    if totalM2 > 0
      promedioM2 = totalPesos / totalM2   
    else
      promedioM2 = 0
    end 
end

def cantCodAmb1
    inicializar
    
    @props = @props.select { |propiedad| propiedad.ambientes == 1 }
    
    @props.size
end

def cantCodAmb2
    inicializar
    
    @props = @props.select { |propiedad| propiedad.ambientes == 2 }
    
    @props.size
end

def cantCodAmb3
    inicializar
    
    @props = @props.select { |propiedad| propiedad.ambientes == 3 }
    
    @props.size
end

def cantCodAmb4
    inicializar
    
    @props = @props.select { |propiedad| propiedad.ambientes != nil }
    @props = @props.select { |propiedad| propiedad.ambientes >= 4 }
    
    @props.size
end

def inicializar
    @props = Propiedad.all

    @props = @props.select { |propiedad|
       (propiedad.fecha_publicacion < Time.now) && (propiedad.fecha_finalizacion > Time.now) && (propiedad.estado_id == 1)
    }

    @props = @props.select { |propiedad| propiedad.barrio_id == id }
    @props = @props.select { |propiedad| propiedad.operacion_id == 1 }
end

app/controllers/barrios_controller.rb
class BarriosController < ApplicationController
  before_action :set_barrio, only: [:show, :edit, :update, :destroy]

  # GET /barrios
  # GET /barrios.json
  def index
    @barrios = Barrio.all
  end

  # GET /barrios/1
  # GET /barrios/1.json
  def show
  end

  # GET /barrios/new
  def new
    @barrio = Barrio.new
  end

  # GET /barrios/1/edit
  def edit
  end

  # POST /barrios
  # POST /barrios.json
  def create
    @barrio = Barrio.new(barrio_params)

    respond_to do |format|
      if @barrio.save
        format.html { redirect_to @barrio, notice: 'Barrio was successfully created.' }
        format.json { render :show, status: :created, location: @barrio }
      else
        format.html { render :new }
        format.json { render json: @barrio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /barrios/1
  # PATCH/PUT /barrios/1.json
  def update
    respond_to do |format|
      if @barrio.update(barrio_params)
        format.html { redirect_to @barrio, notice: 'Barrio was successfully updated.' }
        format.json { render :show, status: :ok, location: @barrio }
      else
        format.html { render :edit }
        format.json { render json: @barrio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /barrios/1
  # DELETE /barrios/1.json
  def destroy
    @barrio.destroy
    respond_to do |format|
      format.html { redirect_to barrios_url, notice: 'Barrio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_barrio
      @barrio = Barrio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def barrio_params
      params.require(:barrio).permit(:nombre)
    end
end

app/helpers/barrios_helper.rb
module BarriosHelper
end

app/views/barrios/_form.html.erb
<%= form_for(@barrio) do |f| %>
  <% if @barrio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barrio.errors.count, "error") %> prohibited this barrio from being saved:</h2>

      <ul>
      <% @barrio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/barrios/edit.html.erb
<h1>Editing barrio</h1>

<%= render 'form' %>

<%= link_to 'Show', @barrio %> |
<%= link_to 'Back', barrios_path %>

app/views/barrios/index.html.erb
<h1>Listing barrios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @barrios.each do |barrio| %>
      <tr>
        <td><%= barrio.nombre %></td>
        <td><%= link_to 'Show', barrio %></td>
        <td><%= link_to 'Edit', edit_barrio_path(barrio) %></td>
        <td><%= link_to 'Destroy', barrio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Barrio', new_barrio_path %>

app/views/barrios/new.html.erb
<h1>New barrio</h1>

<%= render 'form' %>

<%= link_to 'Back', barrios_path %>

app/views/barrios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @barrio.nombre %>
</p>

<%= link_to 'Edit', edit_barrio_path(@barrio) %> |
<%= link_to 'Back', barrios_path %>