config/routes.rb
Rails.application.routes.draw do
  resources :videos

  devise_for :users
  resources :tieneamenities

  resources :amenities

  get 'api/mostrarJson'
  get 'api/mostrarjson' => 'api#mostrarJson'
  get 'propiedades' => 'api#mostrarJson'
  
  get 'propiedads/:id/pausar' => 'propiedads#pausar', as: 'pausar'
  get 'propiedads/:id/reanudar' => 'propiedads#reanudar', as: 'reanudar'
  get 'propiedads/:id/finalizar' => 'propiedads#finalizar', as: 'finalizar'
  get 'propiedads/:id/republicar' => 'propiedads#republicar', as: 'republicar'  
  
  get 'propiedads/filtro'
  
  get 'propiedads/estadisticasBarrio'
  
  resources :operacions

  resources :monedas

  resources :fotos

  resources :tipo_propiedads

  resources :propiedads do
    resources :fotos
  end

  resources :barrios

  get 'welcome/index'
  
  get '/piechart' => 'piechart#piechart'
  get '/columnchart' => 'columnchart#columnchart'
  get '/columnchartprueba' => 'columnchartprueba#columnchartprueba'
  get '/piechartprueba' => 'piechartprueba#piechartprueba'

  root 'welcome#index'

end

app/models/foto.rb
require 'carrierwave/orm/activerecord'
require 'file_size_validator'

class Foto < ActiveRecord::Base
  belongs_to :propiedad
  mount_uploader :nombre, FotoUploader
  validates :nombre, :file_size => {
      :maximum => 5.megabytes.to_i
    }
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  before_action :set_foto, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:new, :edit, :update, :create, :destroy]
  before_action :usuarioValido , only: [:edit, :update, :destroy]

  # GET /fotos
  # GET /fotos.json
  def index
    @fotos = Foto.all
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
  end

  # GET /fotos/new
  def new
    @foto = Foto.new
  end

  # GET /fotos/1/edit
  def edit
  end

  # POST /fotos
  # POST /fotos.json
  def create
    @propiedad = Propiedad.find(params[:propiedad_id])

    if(@propiedad.fotos.count >= TipoPublicacion.find(@propiedad.tipo_publicacion).maxFotos)
      redirect_to propiedad_path(@propiedad), alert: 'No se puede cargar más fotos.'
    else
      @foto = @propiedad.fotos.create(foto_params)
      redirect_to propiedad_path(@propiedad)
    end
  end

  # PATCH/PUT /fotos/1
  # PATCH/PUT /fotos/1.json
  def update
    respond_to do |format|
      if @foto.update(foto_params)
        format.html { redirect_to @foto, notice: 'La foto fue actualizada exitosamente.' }
        format.json { render :show, status: :ok, location: @foto }
      else
        format.html { render :edit }
        format.json { render json: @foto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fotos/1
  # DELETE /fotos/1.json
  def destroy
    propiedad = @foto.propiedad
    @foto.destroy
    respond_to do |format|
    # format.html { redirect_to fotos_url, notice: 'Foto was successfully destroyed.' }
      format.html { redirect_to propiedad_path(propiedad), notice: 'La foto fue eliminada exitosamente.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_foto
    @foto = Foto.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def foto_params
    params.require(:foto).permit(:nombre, :propiedad_id)
  end
  
  def usuarioValido   
    if @foto.propiedad.user_id != current_user.id
      redirect_to propiedads_url, alert: 'La propiedad no pertenece a este usuario.'
    end
  end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
<% if @foto.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

	<ul>
		<% @foto.errors.full_messages.each do |message| %>
		<li>
			<%= message %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="field">
	<%= f.label :nombre %>
	<br>
	<%= f.text_field :nombre %>
</div>
<div class="field">
	<%= f.label :propiedad_id %>
	<br>
	<%= f.text_field :propiedad_id, :name =>  "propiedad_id"%>
</div>
<div class="actions">
	<%= f.submit,"Buscar" %>
</div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<h1>Listing fotos</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Propiedad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fotos.each do |foto| %>
      <tr>
        <td><%= foto.nombre %></td>
        <td><%= foto.propiedad.direccion %></td>
        <td><%= link_to 'Show', foto %></td>
        <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
        <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @foto.nombre %>
</p>

<p>
  <strong>Propiedad:</strong>
  <%= @foto.propiedad.direccion %>
</p>

<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>